/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d37f6cb3581800b3cc97be3
*
* You will get 10% discount for each one of your friends
* 
*/
package com.rjdemo.db.rjdemo_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE SsnotesBase PLEASE EDIT ../Ssnotes.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Ssnotes object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.rjdemo.db.rjdemo_db.entity.Ssnotes;

public class SsnotesBase implements RowMapper<Ssnotes>{
	
	private Long _id;
	
	// Attributes
    private String Author;
    private String CoverImage;
    private Date DatePublished;
    private String Description;
    private String title;
	
	// Relations login
	private String login;
	
	
	
	@Override
	public Ssnotes mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Ssnotes obj = new Ssnotes();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setAuthor(rs.getString("Author"));
			obj.setCoverImage(rs.getString("CoverImage"));
			obj.setDatePublished(rs.getDate("DatePublished"));
			obj.setDescription(rs.getString("Description"));
			obj.setTitle(rs.getString("title"));
			
        	
        	// Relations 1:m login
			obj.setLogin(rs.getString("login"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getAuthor() {
		return Author;
	}


	public void setAuthor(String Author) {
		this.Author = Author;
	}
	public String getCoverImage() {
		return CoverImage;
	}


	public void setCoverImage(String CoverImage) {
		this.CoverImage = CoverImage;
	}
	public Date getDatePublished() {
		return DatePublished;
	}


	public void setDatePublished(Date DatePublished) {
		this.DatePublished = DatePublished;
	}
	public String getDescription() {
		return Description;
	}


	public void setDescription(String Description) {
		this.Description = Description;
	}
	public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}
	
    
    // Relations 1:m login
	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}
    
    
    
    
}