/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d37f6cb3581800b3cc97be3
*
* You will get 10% discount for each one of your friends
* 
*/
// START - USED SERVICES
/*
 *	ssnotesService.create
 *		PARAMS: 
 *		
 *
 *	ssnotesService.get
 *		PARAMS: 
 *					ObjectId id - Id 
 *		
 *
 *	ssnotesService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * ssnotesService  
 */
// END - REQUIRED RESOURCES

app.controller('ssnotesEditController', ['$scope', '$location', '$routeParams', '$q', 'ssnotesService', 'UserService',
    function ($scope, $location, $routeParams, $q, ssnotesService , UserService) {

    	//manage create and save
		$scope.external = {};
		
    	if ($routeParams.id != 'new')
    	{
        	$scope.id = $routeParams.id;
        	$scope.obj = ssnotesService.get({_id: $scope.id});
        	
    	}
    	else{
    		$scope.obj = new ssnotesService();
        	
    	}
    	
    	$scope.save = function(){
    		$scope.obj.$save().then(function(data){
    			$scope.obj=data;
        		$location.path('/ssnoteses/');
    		});
    	}
    	
    	$scope.remove = function(){
    		ssnotesService.remove({_id: $scope.obj._id}).$promise.then(function(){
				$('#removeModal').modal('hide');
				$('.modal-backdrop').remove();
				$('.modal-open').removeClass("modal-open");
        		$location.path('/ssnoteses/');
    		});
    	}
    	
    		
        //manage relation login
        		
    	$scope.list_User = UserService.query();

}]);