/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d37f6cb3581800b3cc97be3
*
* You will get 10% discount for each one of your friends
* 
*/
package com.rjdemo.controller.base;

import java.util.List;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import java.util.ArrayList;
import org.springframework.security.access.annotation.Secured;
import org.springframework.beans.factory.annotation.Autowired;
import com.rjdemo.db.rjdemo_db.service.SsnotesService;
import com.rjdemo.db.rjdemo_db.entity.Ssnotes;

//IMPORT RELATIONS
import com.rjdemo.db.rjdemo_db.entity.User;

public class SsnotesBaseController {
    
    @Autowired
	SsnotesService ssnotesService;



//CRUD METHODS


    //CRUD - CREATE
    @Secured({ "ROLE_PRIVATE_USER" })
		@RequestMapping(value = "/ssnotes", method = RequestMethod.POST, headers = "Accept=application/json")
	public Ssnotes insert(@RequestBody Ssnotes obj) {
		Ssnotes result = ssnotesService.insert(obj);

	    
		
		return result;
	}

	
    //CRUD - REMOVE
    @Secured({ "ROLE_PRIVATE_USER" })
	@RequestMapping(value = "/ssnotes/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
	public void delete(@PathVariable("id") Long id) {
		ssnotesService.delete(id);
	}
	
	
    //CRUD - GET ONE
    @Secured({ "ROLE_PRIVATE_USER" })
	@RequestMapping(value = "/ssnotes/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
	public Ssnotes get(@PathVariable Long id) {
		Ssnotes obj = ssnotesService.get(id);
		
		
		
		return obj;
	}
	
	
    //CRUD - GET LIST
    @Secured({ "ROLE_PRIVATE_USER" })
	@RequestMapping(value = "/ssnotes", method = RequestMethod.GET, headers = "Accept=application/json")
	public List<Ssnotes> getList() {
		return ssnotesService.getList();
	}
	
	

    //CRUD - EDIT
    @Secured({ "ROLE_PRIVATE_USER" })
	@RequestMapping(value = "/ssnotes/{id}", method = RequestMethod.POST, headers = "Accept=application/json")
	public Ssnotes update(@RequestBody Ssnotes obj, @PathVariable("id") Long id) {
		Ssnotes result = ssnotesService.update(obj, id);

	    
		
		return result;
	}
	


/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Custom.js
 */


	
}
